# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-23 03:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='studies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gsheet_id', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('year', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('authors', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('country', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('area', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('population', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('age', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('number_affected', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('diagnostic_criteria', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('pct_with_normal_iq', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('gender_ratio', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('prevalence_rate', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('confidence_interval', models.CharField(blank=True, default='', max_length=255, null=True)),
            ],
        ),
    ]
