# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-05 18:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autism_prevalence_map', '0002_auto_20180823_0344'),
    ]

    operations = [
        migrations.AddField(
            model_name='studies',
            name='year_number',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
