# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-05 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autism_prevalence_map', '0003_studies_year_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='studies',
            name='population_number',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='studies',
            name='prevalence_rate_number',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
