# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-18 17:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autism_prevalence_map', '0004_auto_20180905_1834'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studies',
            old_name='population',
            new_name='study_size',
        ),
        migrations.RenameField(
            model_name='studies',
            old_name='population_number',
            new_name='study_size_number',
        ),
        migrations.RenameField(
            model_name='studies',
            old_name='year',
            new_name='year_of_publication',
        ),
        migrations.RenameField(
            model_name='studies',
            old_name='year_number',
            new_name='year_of_publication_number',
        ),
        migrations.AddField(
            model_name='studies',
            name='category',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studies',
            name='education_level_of_participants',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studies',
            name='erics_quality_assessment',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studies',
            name='erics_reasons_for_lower_quality',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studies',
            name='link_to_news_coverage_by_spectrum',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studies',
            name='mean_income_of_participants',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studies',
            name='methodology',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studies',
            name='reliability_quality',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studies',
            name='time_period_studied',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studies',
            name='time_period_studied_number_max',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AddField(
            model_name='studies',
            name='time_period_studied_number_min',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AddField(
            model_name='studies',
            name='url',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
