# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-18 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autism_prevalence_map', '0005_auto_20180918_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='studies',
            name='citation',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
