# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-19 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autism_prevalence_map', '0006_studies_citation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studies',
            old_name='category',
            new_name='categoryadpddorasd',
        ),
        migrations.RenameField(
            model_name='studies',
            old_name='diagnostic_criteria',
            new_name='diagnosticcriteria',
        ),
        migrations.RenameField(
            model_name='studies',
            old_name='education_level_of_participants',
            new_name='educationlevelofparticipants',
        ),
        migrations.RenameField(
            model_name='studies',
            old_name='erics_quality_assessment',
            new_name='ericsqualityassessment',
        ),
        migrations.RenameField(
            model_name='studies',
            old_name='erics_reasons_for_lower_quality',
            new_name='ericsreasonsbasedonmyrecallofthestudies',
        ),
        migrations.RenameField(
            model_name='studies',
            old_name='number_affected',
            new_name='individualswithautism',
        ),
        migrations.RenameField(
            model_name='studies',
            old_name='mean_income_of_participants',
            new_name='meanincomeofparticipants',
        ),
        migrations.RenameField(
            model_name='studies',
            old_name='pct_with_normal_iq',
            new_name='percentwaverageiq',
        ),
        migrations.RenameField(
            model_name='studies',
            old_name='prevalence_rate',
            new_name='prevalenceper10000',
        ),
        migrations.RenameField(
            model_name='studies',
            old_name='prevalence_rate_number',
            new_name='prevalenceper10000_number',
        ),
        migrations.RenameField(
            model_name='studies',
            old_name='reliability_quality',
            new_name='recommended',
        ),
        migrations.RenameField(
            model_name='studies',
            old_name='study_size',
            new_name='samplesize',
        ),
        migrations.RenameField(
            model_name='studies',
            old_name='study_size_number',
            new_name='samplesize_number',
        ),
        migrations.RenameField(
            model_name='studies',
            old_name='gender_ratio',
            new_name='sexratiomf',
        ),
        migrations.RenameField(
            model_name='studies',
            old_name='year_of_publication',
            new_name='yearpublished',
        ),
        migrations.RenameField(
            model_name='studies',
            old_name='year_of_publication_number',
            new_name='yearpublished_number',
        ),
        migrations.RenameField(
            model_name='studies',
            old_name='time_period_studied',
            new_name='yearsstudied',
        ),
        migrations.RenameField(
            model_name='studies',
            old_name='time_period_studied_number_max',
            new_name='yearsstudied_number_max',
        ),
        migrations.RenameField(
            model_name='studies',
            old_name='time_period_studied_number_min',
            new_name='yearsstudied_number_min',
        ),
        migrations.RemoveField(
            model_name='studies',
            name='confidence_interval',
        ),
        migrations.RemoveField(
            model_name='studies',
            name='link_to_news_coverage_by_spectrum',
        ),
        migrations.RemoveField(
            model_name='studies',
            name='methodology',
        ),
        migrations.RemoveField(
            model_name='studies',
            name='url',
        ),
        migrations.AddField(
            model_name='studies',
            name='commentsfromotheradvisors',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studies',
            name='confidenceinterval',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studies',
            name='link1title',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studies',
            name='link1url',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studies',
            name='link2title',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studies',
            name='link2url',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studies',
            name='link3title',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studies',
            name='link3url',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studies',
            name='link4title',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studies',
            name='link4url',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studies',
            name='sourceofdataforthisspreadsheet',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studies',
            name='studytype',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
