# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-26 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autism_prevalence_map', '0007_auto_20181019_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='studies',
            name='num_yearsstudied',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
