# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-12-03 00:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autism_prevalence_map', '0008_studies_num_yearsstudied'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studies',
            name='commentsfromotheradvisors',
        ),
        migrations.RemoveField(
            model_name='studies',
            name='ericsqualityassessment',
        ),
        migrations.RemoveField(
            model_name='studies',
            name='ericsreasonsbasedonmyrecallofthestudies',
        ),
        migrations.RemoveField(
            model_name='studies',
            name='sourceofdataforthisspreadsheet',
        ),
    ]
