# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2023-01-31 20:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autism_prevalence_map', '0009_auto_20211203_0041'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studies',
            options={'verbose_name': 'Study', 'verbose_name_plural': 'Studies'},
        ),
        migrations.AddField(
            model_name='studies',
            name='last_update',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='studies',
            name='categoryadpddorasd',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Category (AD, PDD or ASD)'),
        ),
        migrations.AlterField(
            model_name='studies',
            name='confidenceinterval',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='95% Confidence interval'),
        ),
        migrations.AlterField(
            model_name='studies',
            name='diagnosticcriteria',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Diagnostic Criteria'),
        ),
        migrations.AlterField(
            model_name='studies',
            name='diagnostictools',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Diagnostic Tools'),
        ),
        migrations.AlterField(
            model_name='studies',
            name='educationlevelofparticipants',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Education'),
        ),
        migrations.AlterField(
            model_name='studies',
            name='individualswithautism',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Individuals with Autism'),
        ),
        migrations.AlterField(
            model_name='studies',
            name='link1title',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Link 1 Title'),
        ),
        migrations.AlterField(
            model_name='studies',
            name='link1url',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Link 1 Url'),
        ),
        migrations.AlterField(
            model_name='studies',
            name='link2title',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Link 2 Title'),
        ),
        migrations.AlterField(
            model_name='studies',
            name='link2url',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Link 2 Url'),
        ),
        migrations.AlterField(
            model_name='studies',
            name='link3title',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Link 3 Title'),
        ),
        migrations.AlterField(
            model_name='studies',
            name='link3url',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Link 3 Url'),
        ),
        migrations.AlterField(
            model_name='studies',
            name='link4title',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Link 4 Title'),
        ),
        migrations.AlterField(
            model_name='studies',
            name='link4url',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Link 4 Url'),
        ),
        migrations.AlterField(
            model_name='studies',
            name='meanincomeofparticipants',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Income'),
        ),
        migrations.AlterField(
            model_name='studies',
            name='percentwaverageiq',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Percent w/ Average IQ'),
        ),
        migrations.AlterField(
            model_name='studies',
            name='prevalenceper10000',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Prevalence (per 10,000)'),
        ),
        migrations.AlterField(
            model_name='studies',
            name='samplesize',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Sample Size'),
        ),
        migrations.AlterField(
            model_name='studies',
            name='sexratiomf',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Sex ratio (M:F)'),
        ),
        migrations.AlterField(
            model_name='studies',
            name='studytype',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Study Type'),
        ),
        migrations.AlterField(
            model_name='studies',
            name='yearpublished',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Year Published'),
        ),
        migrations.AlterField(
            model_name='studies',
            name='yearsstudied',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Year(s) Studied'),
        ),
    ]
