# Generated by Django 2.2.28 on 2025-04-03 08:29

from django_ckeditor_5.fields import CKEditor5Field
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autism_prevalence_map', '0011_auto_20230203_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='About the Global Autism Prevalence Map', help_text='Main title of the About page', max_length=255)),
                ('meta_title', models.CharField(blank=True, default='', help_text='SEO meta title (up to 60 characters recommended)', max_length=255)),
                ('meta_description', models.TextField(blank=True, default='', help_text='SEO meta description (up to 160 characters recommended)')),
            ],
            options={
                'verbose_name': 'About Page',
                'verbose_name_plural': 'About Pages',
            },
        ),
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('text', 'Text Block'), ('toc', 'Table of Contents')], default='text', help_text='Type of section', max_length=20)),
                ('title', models.CharField(blank=True, help_text='Section title (used for Table of Contents sections)', max_length=255)),
                ('content', CKEditor5Field(blank=True, help_text='Rich text content (used for Text Block sections)')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of this section')),
                ('links', models.TextField(blank=True, help_text='Enter links for Table of Contents sections as: link_text|link_url,link_text|link_url')),
                ('about_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='autism_prevalence_map.AboutPage')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
