# Generated by Django 3.2.5 on 2025-04-20 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autism_prevalence_map', '0011_auto_20230203_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='studies',
            name='age_high',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studies',
            name='age_low',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studies',
            name='confidenceinterval_high',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studies',
            name='confidenceinterval_low',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studies',
            name='individualswithautism_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studies',
            name='percentwaverageiq_number',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studies',
            name='sexratiomf_number',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
