# Generated by Django 2.2.28 on 2025-04-05 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autism_prevalence_map', '0012_aboutpage_aboutsection'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='meta_thumbnail',
            field=models.ImageField(blank=True, help_text='Image to use as the social media thumbnail (recommended size: 1200x630 pixels)', null=True, upload_to='about_thumbnails/'),
        ),
    ]
