# Generated by Django 3.2.5 on 2025-04-07 19:16

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autism_prevalence_map', '0013_aboutpage_meta_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutsection',
            name='newsletter_support_line',
            field=models.CharField(blank=True, default='Stay up to date with the latest autism research news.', help_text='Support line for Newsletter section (used for Newsletter sections)', max_length=255),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='newsletter_title',
            field=models.CharField(blank=True, default='Subscribe to our Newsletter', help_text='Title for Newsletter section (used for Newsletter sections)', max_length=255),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Rich text content (used for Text Block and Callout Box sections)'),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='section_type',
            field=models.CharField(choices=[('text', 'Text Block'), ('toc', 'Table of Contents'), ('callout', 'Callout Box'), ('newsletter', 'Newsletter')], default='text', help_text='Type of section', max_length=20),
        ),
        migrations.AlterField(
            model_name='options',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='studies',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
