# Generated by Django 3.2.5 on 2025-04-08 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autism_prevalence_map', '0014_auto_20250407_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutsection',
            name='section_title_id',
            field=models.CharField(blank=True, help_text='ID attribute for the Section Title (used for Section Title sections)', max_length=255),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='section_title_text',
            field=models.CharField(blank=True, help_text='Text for the Section Title (used for Section Title sections)', max_length=255),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='newsletter_support_line',
            field=models.CharField(blank=True, default='Catch up on what you may have missed from our recent coverage.', help_text='Support copy for newsletter section.', max_length=255),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='newsletter_title',
            field=models.CharField(blank=True, default='Sign up for our weekly newsletter.', help_text='Title for newsletter section.', max_length=255),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='section_type',
            field=models.CharField(choices=[('section_title', 'Section Title'), ('text', 'Text Block'), ('toc', 'Table of Contents'), ('callout', 'Special Callout'), ('newsletter', 'Newsletter')], default='text', help_text='Type of section', max_length=20),
        ),
    ]
