# Generated by Django 3.2.5 on 2025-04-09 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autism_prevalence_map', '0015_auto_20250408_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutsection',
            name='newsletter_id',
            field=models.PositiveIntegerField(blank=True, default=2, help_text='Newsletter ID (value: 2 for Spectrum weekly newsletter)'),
        ),
    ]
