# Generated by Django 3.2.5 on 2025-08-22 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autism_prevalence_map', '0016_aboutsection_newsletter_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('middle_text', models.TextField(default='Have you recently published new research in neuroscience?', help_text='Text for the middle section of the footer')),
                ('middle_button_text', models.CharField(default='Let us know', help_text='Button text for the middle section', max_length=255)),
                ('middle_button_link', models.URLField(default='https://www.thetransmitter.org/contact-us/', help_text='Button link for the middle section', max_length=500)),
                ('bottom_tagline', models.CharField(default='Curating neuroscience, connecting community', help_text='Tagline text below the logo', max_length=255)),
                ('bottom_support_text', models.CharField(default='An editorially independent publication supported by the Simons Foundation', help_text='Support text at the very bottom', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Footer',
                'verbose_name_plural': 'Footers',
            },
        ),
        migrations.CreateModel(
            name='FooterLeftMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Menu item title (HTML allowed, e.g., <em>The Transmitter</em> books)', max_length=255)),
                ('url', models.URLField(help_text='Menu item URL', max_length=500)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of this menu item (lower numbers appear first)')),
                ('footer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='left_menu_items', to='autism_prevalence_map.footer')),
            ],
            options={
                'verbose_name': 'Footer Left Menu Item',
                'verbose_name_plural': 'Footer Left Menu Items',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FooterRightMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Menu item title (HTML allowed, e.g., About <em>The Transmitter</em>)', max_length=255)),
                ('url', models.URLField(help_text='Menu item URL', max_length=500)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of this menu item (lower numbers appear first)')),
                ('footer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='right_menu_items', to='autism_prevalence_map.footer')),
            ],
            options={
                'verbose_name': 'Footer Right Menu Item',
                'verbose_name_plural': 'Footer Right Menu Items',
                'ordering': ['order'],
            },
        ),
    ]
