# Generated by Django 3.2.5 on 2025-08-27 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autism_prevalence_map', '0017_footer_content_management'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='middle_subtext',
            field=models.CharField(default='We want to hear from you.', help_text='Subtext for the middle section of the footer', max_length=255),
        ),
    ]
