# Generated by Django 3.2.5 on 2025-09-17 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autism_prevalence_map', '0012_auto_20250420_1208'),
        ('autism_prevalence_map', '0018_footer_middle_subtext'),
    ]

    operations = [
    ]
